/*
 * Copyright (c) 2020, JavaFamily Technology Corp, All Rights Reserved.
 *
 * The software and information contained herein are copyrighted and
 * proprietary to JavaFamily Technology Corp. This software is furnished
 * pursuant to a written license agreement and may be used, copied,
 * transmitted, and stored only in accordance with the terms of such
 * license and with the inclusion of the above copyright notice. Please
 * refer to the file "COPYRIGHT" for further copyright and licensing
 * information. This software and information or any other copies
 * thereof may not be provided or otherwise made available to any other
 * person.
 */

/*
 * This file is automatically generated. Do not edit this file directly. Modify the
 * index.components section of index.yaml instead
 * Run "ant angular.generate-index-files" in the build directory to update the generated
 * file.
 */

import { Type } from "@angular/core";
import { MatMessageDialog } from "./dialog/mat-message-dialog";
import { ExportDialog } from "./export-dialog/export-dialog";
import { ActionsContextmenuComponent } from "./fixed-dropdown/actions-contextmenu.component";
import { MatTableView } from "./mat-table-view/mat-table-view.component";
import { ModalHeaderComponent } from "./modal-header/modal-header.component";
import { ApplyButtonComponent } from "./slide-out/apply-button.component";
import { DropdownView } from "./dropdown-view/dropdown-view.component";
import { ErrorComponent } from "./error/error.component";
import { FixedDropdownComponent } from "./fixed-dropdown/fixed-dropdown.component";
import { FixedDropdownContextmenuComponent } from "./fixed-dropdown/fixed-dropdown-contextmenu.component";
import { MessageDialog } from "./dialog/message-dialog.component";
import { NotificationsComponent } from "./notification/notifications.component";
import { RepositoryTreeComponent } from "./tree/repository-tree.component";
import { SlideOutBackdropComponent } from "./slide-out/slide-out-backdrop.component";
import { SlideOutComponent } from "./slide-out/slide-out.component";
import { SplitPaneComponent } from "./split/split-pane.component";
import { TooltipComponent } from "./tooltip/tooltip.component";
import { TreeNodeComponent } from "./tree/node/tree-node.component";

export const MODULE_COMPONENTS: Type<any>[] = [
   ActionsContextmenuComponent,
   ApplyButtonComponent,
   DropdownView,
   ErrorComponent,
   ExportDialog,
   FixedDropdownComponent,
   FixedDropdownContextmenuComponent,
   MessageDialog,
   MatMessageDialog,
   MatTableView,
   ModalHeaderComponent,
   NotificationsComponent,
   RepositoryTreeComponent,
   SlideOutBackdropComponent,
   SlideOutComponent,
   SplitPaneComponent,
   TooltipComponent,
   TreeNodeComponent
];
