#!/usr/bin/env sh

./gradlew clean bootJar -x test -Pbuildenv=prod --no-daemon --console plain

# build docker image

echo JF_JASYPT_ENCRYPTOR Token is: $JF_JASYPT_ENCRYPTOR

docker build --build-arg JF_JASYPT_ENCRYPTOR=$JF_JASYPT_ENCRYPTOR --build-arg JF_GITHUB_CLIENT_ID=$JF_GITHUB_CLIENT_ID --build-arg JF_GITHUB_CLIENT_SECRETS=$JF_GITHUB_CLIENT_SECRETS -f ./Dockerfile -m 1g -t javafamily/jfoa ./runner/build/libs/
