#!/usr/bin/env sh

./gradlew clean bootJar -x test -Pbuildenv=prod --no-daemon --console plain

# build docker image
docker build -f ./Dockerfile -t javafamily/jfoa ./runner/build/libs/

# publish to docker hub, login first
docker login -u javafamily -p dreamLi0812!@#
docker push javafamily/jfoa:latest
