# Cache Config
spring:
   cache:
      ehcache:
         config: classpath:ehcache.xml
      type: ehcache

ds:
   # Hibernate config
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      formatSql: true
      show-sql: true
   # Datasource
   druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql

---

spring:
   profiles: prod
server:
   port: 80

ds:
   hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
   druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.56.42.60:3306/db_jfoa?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

---

spring:
   profiles: dev

server:
   port: 8080

ds:
   hibernate:
      dialect: org.hibernate.dialect.H2Dialect
   druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./build/resources/main/jfoadb/jfoa_db
      username: jfoa
      password: jfoa

---

spring:
   profiles: test

server:
   port: 10001

ds:
   hibernate:
      dialect: org.hibernate.dialect.H2Dialect
   druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./build/resources/test/jfoadb/jfoa_db
      username: jfoa
      password: jfoa
