jasypt:
   encryptor:
      password: ${JF_JASYPT_ENCRYPTOR}

jfoa:
   amqp:
      override: false

   oauth:
      callback: http://javafamily.club/public/oauth/callback

      github:
         url: https://github.com/login/oauth/authorize
         client-id: ${JF_GITHUB_CLIENT_ID}
         client-secrets: ${JF_GITHUB_CLIENT_SECRETS}

      dingTalk:
         url: 'https://oapi.dingtalk.com/connect/qrconnect'
         client-id: 'dingoabphullwtsdwq60ts'
         client-secrets: 'OpcVkD2v333jgbvsrJu4aQzv7jKgK4HKy4uBb9gX0au4Bavoyy61YEEs-iO2eNra'

   thread:
      maxSize: 10
      waitTasksComplete: true
      prefix: "jfoa-"

   server:
      dump-interval: 1000
      dump-count: 60

   http:
      maxTotalConnect: 100
      maxConnectPerRoute: 40
      connectTimeout: 60000
      readTimeout: 60000
      connectionRequestTimout: 60000
      retryTimes: 3
      charset: UTF-8
      keepAliveTime: 60
      keepAliveTargetHost:
         www.github.com: 60
         api.github.com: 60

spring:
#   devtools:
#      restart:
#         additional-paths:
#            - src/main/java
#            - application.yml
#         exclude: static/**,jfoadb/**

   # Cache Config
   cache:
      ehcache:
         config: classpath:ehcache.xml
      type: ehcache

   # multipart config
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

   # Rabbitmq
   rabbitmq:
      host: javafamily.club
      port: 5672
      virtual-host: /
      username: jfoa
      password: ENC(Fsj3Z7OHFAvOfjf7GSol02jS6ddGr9HSVAm1fBx8iwig942jxj5goh/8QJFrRq2p)

   # Redis
   redis:
      host: javafamily.club
      port: 6379
      database: 0
   # Message
   messages:
      basename: i18n.messages
   # Quartz
   quartz:
      scheduler-name: JavaFamily-Scheduler
      job-store-type: memory
      overwriteExistingJobs: true
      wait-for-jobs-to-complete-on-shutdown: true
      startupDelay: 10
      jdbc:
         initialize-schema: never

ds:
   # Hibernate config
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      formatSql: true
      show-sql: true
   # Datasource
   druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql

# logging to file
logging:
   file: ./logs/jfoa-log.log
   level:
      root: info
      club.javafamily: info

# Server
server:
   max-http-header-size: 1MB
   tomcat:
      uri-encoding: UTF-8
      max-http-post-size: 3MB
      max-swallow-size: 3MB

---

# related ssl enable config by property 'jfoa.server.sslEnable' and `server.ssl.enabled`
server:
   port: 80

# SSL
   ssl:
      # disable ssl default
      enabled: false
      key-store: classpath:/config/ssl/javafamily.club.pfx
      key-store-password: jj5qDzz4
      key-store-type: PKCS12

jfoa:
   oauth:
      callback: http://javafamily.club/public/oauth/callback

      github:
         client-id: ${JF_GITHUB_CLIENT_ID}
         client-secrets: ${JF_GITHUB_CLIENT_SECRETS}

spring:
   profiles: prod

   # Mail Config
   mail:
      host: smtp.office365.com
      port: 587
      default-encoding: utf-8
      username: javafamily.no-reply@outlook.com
      password: ENC(Dei9QlGM89UdMyvlvEXVE6DX9aMKZBlRs+Rt5DXUpH3T10DsKRIUTpEOQDIT/I3j)
      properties:
         mail:
            smtp:
               starttls:
                  enable: true
               ssl:
                  enable: false
                  required: false
               timeout: 80000
               connectiontimeout: 80000
               writetimeout: 80000

ds:
   hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
   druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://javafamily.club:3306/db_jfoa?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ENC(dOtsjEP7GiBc4d8/x0MIbCmV19HshULfCGIUaVKRqrwjckDZQWvLBq6vn7cCdzyR)

---

server:
   port: 80

jfoa:
   oauth:
      callback: http://localhost/public/oauth/callback

      github:
         client-id: ${DEV_JF_GITHUB_CLIENT_ID}
         client-secrets: ${DEV_JF_GITHUB_CLIENT_SECRETS}

      dingTalk:
         url: 'https://oapi.dingtalk.com/connect/qrconnect'
         client-id: 'dingoawl9vntxkndtiwjfr'
         client-secrets: '8DHr6Sy8vVTCvU-a_IM7E2B0X8-W-pxGT-5arUkHBqNCUvW36QpEH1EWtraapOg7'

spring:
   profiles: dev

   # Redis
   redis:
      database: 8

   # rest template
   http:
      log-request-details: true

   # thymeleaf
   thymeleaf:
      cache: false
      session:
         store-type: none

   # Mail Config
   mail:
      host: smtp.qq.com
      port: 465
      default-encoding: utf-8
      username: 243853974@qq.com
      password: ENC(h9Bgd9w/zExbkGHmyOehfYkXQAbr0wu1wWG+o8fg8VfpyPtuQHqtMZmOi98vKIcForQIpMxIzazZoGvRX3Ad+w==)
      properties:
         mail:
            smtp:
               ssl:
                  enable: true
                  required: true
               timeout: 80000
               connectiontimeout: 80000
               writetimeout: 80000

ds:
   hibernate:
      dialect: org.hibernate.dialect.H2Dialect
   druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./build/resources/main/jfoadb/jfoa_db;AUTO_SERVER=TRUE
      username: jfoa
      password: jfoa

logging:
   level:
      root: info
      club.javafamily: info

---

server:
   port: 10001

spring:
   profiles: test

   # Redis
   redis:
      database: 15

   # Mail Config
   mail:
      host: smtp.qq.com
      port: 465
      default-encoding: utf-8
      username: 243853974@qq.com
      password: ENC(h9Bgd9w/zExbkGHmyOehfYkXQAbr0wu1wWG+o8fg8VfpyPtuQHqtMZmOi98vKIcForQIpMxIzazZoGvRX3Ad+w==)
      properties:
         mail:
            smtp:
               ssl:
                  enable: true
                  required: true
               timeout: 80000
               connectiontimeout: 80000
               writetimeout: 80000

ds:
   hibernate:
      dialect: org.hibernate.dialect.H2Dialect
   druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./build/resources/test/jfoadb/jfoa_db;AUTO_SERVER=TRUE
      username: jfoa
      password: jfoa

logging:
   level:
      root: debug
      club.javafamily: debug
