create table Employee (
       id integer generated by default as identity,
        account varchar(255),
        name varchar(255),
        password varchar(255),
        branch_id integer,
        department_id integer,
        primary key (id)
    )

INSERT INTO Employee(account, name, password) values('admin', 'admin', 'df655ad8d3229f3269fad2a8bab59b6c');

