create table Role (
   id integer generated by default as identity,
    name varchar(255),
    primary key (id)
)

create table Employee_Role (
    Employee_id integer not null,
    roles_id integer not null,
    primary key (Employee_id, roles_id)
)

insert into Role(name) values('Administrator');

insert into Employee_Role(Employee_id, roles_id) values(1, 1);
