
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Ruby for Sass
      if: ${{ runner.os == 'Windows' }}
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: ruby env
      if: ${{ runner.os == 'Windows' }}
      run: |
        gem update
        gem install sass
        gem list

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew cleanAll build clean -Pbuildenv=prod --no-daemon --console=plain

    - name: Build Installer
      run: |
        ./gradlew clean installerCompile -x test -Pbuildenv=prod
        ./gradlew buildInstaller -x test -Pbuildenv=prod

    - name: Zip Installer
      run: ./gradlew zipInstaller -Pbuildenv=prod --no-daemon --console=plain

    - name: Publish Installer
      run: ./gradlew publish -Pbuildenv=prod

    - name: Clean Env
      run: ./gradlew cleanAll -Pbuildenv=prod --no-daemon --console=plain
