
name: build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**/*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      JF_JASYPT_ENCRYPTOR: ${{ secrets.JF_JASYPT_ENCRYPTOR }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Ruby for Sass
      if: ${{ runner.os == 'Windows' }}
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: ruby env
      if: ${{ runner.os == 'Windows' }}
      run: |
        gem update
        gem install sass
        gem list

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew cleanAll build -Pbuildenv=prod --no-daemon --console=plain

    - name: Code Coverage
      if: ${{ runner.os == 'Linux' }}
      run: bash <(curl -s https://codecov.io/bash)

    # upload build text reports
    - name: Publish to github artifact
      uses: actions/upload-artifact@v2
      with:
        name: jfoa-build-reports-${{ runner.os }}
        path: runner/build/reports/

    - name: Clean Env
      run: ./gradlew cleanAll -Pbuildenv=prod --no-daemon --console=plain
