
name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew buildDockerImage Dockerfile

    - name: Build Docker Image with Gradle
      run: ./buildDockerImage

    - name: Push image to docker hub
      run: |
        docker login -u javafamily -p ${{ secrets.JF_DOCKER_HUB_PWD }}
        docker push javafamily/jfoa:latest

    - name: Clean Env
      run: ./gradlew cleanAll
