# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Mac'Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew cleanAll build clean -Pbuildenv=prod --no-daemon --console=plain

    - name: Build Installer
      run: |
        ./gradlew clean installerCompile -x test -Pbuildenv=prod
        ./gradlew buildInstaller -x test -Pbuildenv=prod

    - name: Zip Installer
      run: ./gradlew zipInstaller -Pbuildenv=prod --no-daemon --console=plain

    - name: Publish Installer
      run: ./gradlew publish -Pbuildenv=prod

    - name: Clean Env
      run: ./gradlew cleanAll -Pbuildenv=prod --no-daemon --console=plain


