
# publish artifact reference:
# https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts

# Wildcard Pattern reference:
# https://docs.oracle.com/cd/E19683-01/817-2176-10/dnwldcrd.html

name: publish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**/*'
  release:
    types: [published, edited]

jobs:
  publish:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      JF_NEXUS_PWD: ${{ secrets.JF_NEXUS_PWD }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Ruby for Sass
      if: ${{ runner.os == 'Windows' }}
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: ruby env
      if: ${{ runner.os == 'Windows' }}
      run: |
        gem update
        gem install sass
        gem list

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Installer
      run: |
        ./gradlew clean installerCompile -x test -Pbuildenv=prod
        ./gradlew buildInstaller -x test -Pbuildenv=prod

    - name: Zip Installer
      run: ./gradlew zipInstaller -Pbuildenv=prod --no-daemon --console=plain

    # Only release events publish artifacts to the JavaFamily nexus repository.
    - name: Publish Installer
      if: ${{ github.event_name == 'release' }}
      run: ./gradlew publish -Pbuildenv=prod

    - name: Publish to github artifact
      uses: actions/upload-artifact@v2
      with:
        name: jfoa-client-0.0.1-${{ runner.os }}
        path: web/angular/build/installerArchives/jfoa-client-*.zip
        if-no-files-found: error

    # Download and Verify Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: jfoa-client-0.0.1-${{ runner.os }}
        path: web/angular/build/download/artifact

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: web/angular/build/download/artifact
